// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WEB_API_HealTime.Data;

#nullable disable

namespace WEB_API_HealTime.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230407020052_ConfigurandoIndexNoBanco")]
    partial class ConfigurandoIndexNoBanco
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WEB_API_HealTime.Models.ConsultasMedicas.ConsultaAgendada", b =>
                {
                    b.Property<int>("ConsultasAgendadasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsultasAgendadasId"));

                    b.Property<DateTime>("DataConsulta")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("DataSolicitacaoConsulta")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Encaminhamento")
                        .IsRequired()
                        .HasColumnType("CHAR(1)");

                    b.Property<int>("EspecialidadeId")
                        .HasColumnType("int");

                    b.Property<int>("MedicoId")
                        .HasColumnType("int");

                    b.Property<string>("MotivoConsulta")
                        .HasColumnType("VARCHAR(300)");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.Property<int>("StatusConsultaId")
                        .HasColumnType("int");

                    b.HasKey("ConsultasAgendadasId")
                        .HasName("PK_ConsultaAgendadaId");

                    b.HasIndex("EspecialidadeId");

                    b.HasIndex("MedicoId");

                    b.HasIndex("StatusConsultaId");

                    b.ToTable("ConsultasAgendadas");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.ConsultasMedicas.ConsultaCancelada", b =>
                {
                    b.Property<int>("ConsultaCanceladaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsultaCanceladaId"));

                    b.Property<int>("ConsultaAgendadaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCancelamento")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("MotivoCancelamento")
                        .IsRequired()
                        .HasColumnType("VARCHAR(300)");

                    b.HasKey("ConsultaCanceladaId", "ConsultaAgendadaId")
                        .HasName("PK_ConsultaCancelada_ConsultaAgendada");

                    b.HasIndex("ConsultaAgendadaId")
                        .IsUnique();

                    b.ToTable("ConsultaCanceladas");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.ConsultasMedicas.Especialidade", b =>
                {
                    b.Property<int>("EspecialidadeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EspecialidadeId"));

                    b.Property<string>("DescEspecialidade")
                        .IsRequired()
                        .HasColumnType("VARCHAR(25)");

                    b.HasKey("EspecialidadeId")
                        .HasName("PK_EspecialidadeId");

                    b.ToTable("Especialidades");

                    b.HasData(
                        new
                        {
                            EspecialidadeId = 1,
                            DescEspecialidade = "Cardiologia"
                        },
                        new
                        {
                            EspecialidadeId = 2,
                            DescEspecialidade = "Dermatologia"
                        },
                        new
                        {
                            EspecialidadeId = 3,
                            DescEspecialidade = "Ginecologia/Obstetrícia"
                        },
                        new
                        {
                            EspecialidadeId = 4,
                            DescEspecialidade = "Ortopedia"
                        },
                        new
                        {
                            EspecialidadeId = 5,
                            DescEspecialidade = "Anestesiologia"
                        },
                        new
                        {
                            EspecialidadeId = 6,
                            DescEspecialidade = "Pediatria"
                        },
                        new
                        {
                            EspecialidadeId = 7,
                            DescEspecialidade = "Oftalmologia"
                        },
                        new
                        {
                            EspecialidadeId = 8,
                            DescEspecialidade = "Psiquiatria"
                        },
                        new
                        {
                            EspecialidadeId = 9,
                            DescEspecialidade = "Urologia"
                        },
                        new
                        {
                            EspecialidadeId = 10,
                            DescEspecialidade = "Oncologia"
                        },
                        new
                        {
                            EspecialidadeId = 11,
                            DescEspecialidade = "Endocrinologia"
                        },
                        new
                        {
                            EspecialidadeId = 12,
                            DescEspecialidade = "Neurologia"
                        },
                        new
                        {
                            EspecialidadeId = 13,
                            DescEspecialidade = "Hematologia"
                        },
                        new
                        {
                            EspecialidadeId = 14,
                            DescEspecialidade = "Cirurgia Plástica"
                        });
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.ConsultasMedicas.Medico", b =>
                {
                    b.Property<int>("MedicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicoId"));

                    b.Property<string>("CrmMedico")
                        .HasColumnType("CHAR(6)");

                    b.Property<string>("NmMedico")
                        .IsRequired()
                        .HasColumnType("VARCHAR(40)");

                    b.Property<string>("UfCrmMedico")
                        .IsRequired()
                        .HasColumnType("CHAR(2)");

                    b.HasKey("MedicoId")
                        .HasName("PK_MedicoId");

                    b.ToTable("Medicos");

                    b.HasData(
                        new
                        {
                            MedicoId = 1,
                            CrmMedico = "054321",
                            NmMedico = "Dr Val",
                            UfCrmMedico = "SP"
                        },
                        new
                        {
                            MedicoId = 2,
                            CrmMedico = "012345",
                            NmMedico = "Dr Teste",
                            UfCrmMedico = "RJ"
                        });
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.ConsultasMedicas.StatusConsulta", b =>
                {
                    b.Property<int>("StatusConsultaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusConsultaId"));

                    b.Property<string>("DescStatusConsulta")
                        .IsRequired()
                        .HasColumnType("VARCHAR(25)");

                    b.HasKey("StatusConsultaId")
                        .HasName("PK_StatusConsultaId");

                    b.ToTable("StatusConsultas");

                    b.HasData(
                        new
                        {
                            StatusConsultaId = 1,
                            DescStatusConsulta = "Agendada"
                        },
                        new
                        {
                            StatusConsultaId = 2,
                            DescStatusConsulta = "Encerrada"
                        },
                        new
                        {
                            StatusConsultaId = 3,
                            DescStatusConsulta = "Cancelada"
                        },
                        new
                        {
                            StatusConsultaId = 4,
                            DescStatusConsulta = "Remarcada"
                        },
                        new
                        {
                            StatusConsultaId = 5,
                            DescStatusConsulta = "Fila de espera"
                        });
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.Medicacoes.AndamentoMedicacao", b =>
                {
                    b.Property<DateTime>("MtAndamentoMedicacao")
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("PrescricaoPacienteId")
                        .HasColumnType("int");

                    b.Property<int>("MedicacaoId")
                        .HasColumnType("int");

                    b.Property<string>("AcaoMedicacao")
                        .IsRequired()
                        .HasColumnType("CHAR(1)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("QtdeMedicao")
                        .HasColumnType("int");

                    b.HasKey("MtAndamentoMedicacao", "PrescricaoPacienteId", "MedicacaoId")
                        .HasName("PK_AndamentoMedicacao_MtAndamentoMedicacao_PrescricaoPacienteId_MedicacaoId");

                    b.HasIndex("MedicacaoId");

                    b.ToTable("AndamentoMedicacoes");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.Medicacoes.Medicacao", b =>
                {
                    b.Property<int>("MedicacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicacaoId"));

                    b.Property<string>("CompostoAtivoMedicacao")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Generico")
                        .IsRequired()
                        .HasColumnType("CHAR(1)");

                    b.Property<string>("LaboratorioMedicaocao")
                        .IsRequired()
                        .HasColumnType("VARCHAR(80)");

                    b.Property<string>("NomeMedicacao")
                        .IsRequired()
                        .HasColumnType("VARCHAR(80)");

                    b.Property<int>("StatusMedicacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("TipoMedicacaoId")
                        .HasColumnType("int");

                    b.HasKey("MedicacaoId")
                        .HasName("PK_MedicacaoId");

                    b.HasIndex("TipoMedicacaoId");

                    b.ToTable("Medicacoes");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.Medicacoes.PrescricaoMedicacao", b =>
                {
                    b.Property<int>("PrescricaoPacienteId")
                        .HasColumnType("int");

                    b.Property<int>("MedicacaoId")
                        .HasColumnType("int");

                    b.Property<int>("Duracao")
                        .HasColumnType("int");

                    b.Property<int>("Intervalo")
                        .HasColumnType("int");

                    b.Property<int>("Qtde")
                        .HasColumnType("int");

                    b.Property<string>("StatusMedicacaoFlag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(1)")
                        .HasDefaultValue("S");

                    b.HasKey("PrescricaoPacienteId", "MedicacaoId")
                        .HasName("PK_CONCAT_PrescricaPacienteId_MedicacaoId");

                    b.HasIndex("MedicacaoId")
                        .IsUnique();

                    b.ToTable("PrescricoesMedicacoes");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.Medicacoes.PrescricaoPaciente", b =>
                {
                    b.Property<int>("PrescricaoPacienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrescricaoPacienteId"));

                    b.Property<DateTime?>("CriadoEm")
                        .IsRequired()
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("DescFichaPessoa")
                        .HasColumnType("VARCHAR(350)");

                    b.Property<DateTime>("Emissao")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("FlagStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(1)")
                        .HasDefaultValue("S");

                    b.Property<int>("MedicoId")
                        .HasColumnType("int");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Validade")
                        .HasColumnType("datetime2(0)");

                    b.HasKey("PrescricaoPacienteId")
                        .HasName("PK_PrescricaoPacienteId");

                    b.HasIndex("MedicoId");

                    b.HasIndex("PacienteId");

                    b.ToTable("PrescricaoPacientes");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.Medicacoes.TipoMedicacao", b =>
                {
                    b.Property<int>("TipoMedicacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoMedicacaoId"));

                    b.Property<int>("ClasseAplicacao")
                        .HasColumnType("int");

                    b.Property<string>("DescMedicacao")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("TituloTipoMedicacao")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("TipoMedicacaoId")
                        .HasName("PK_TipoMedicacaoId");

                    b.ToTable("TiposMedicacoes");

                    b.HasData(
                        new
                        {
                            TipoMedicacaoId = 1,
                            ClasseAplicacao = 1,
                            DescMedicacao = "Aplicado pela boca",
                            TituloTipoMedicacao = "Via oral"
                        },
                        new
                        {
                            TipoMedicacaoId = 2,
                            ClasseAplicacao = 1,
                            DescMedicacao = "Aplicado  por dembaixo da língua",
                            TituloTipoMedicacao = "Sublingual"
                        },
                        new
                        {
                            TipoMedicacaoId = 3,
                            ClasseAplicacao = 1,
                            DescMedicacao = "Aplicado pelo canal retal",
                            TituloTipoMedicacao = "Supositorios"
                        },
                        new
                        {
                            TipoMedicacaoId = 4,
                            ClasseAplicacao = 2,
                            DescMedicacao = "Aplicada diretamente no sangue",
                            TituloTipoMedicacao = "Intravenosa"
                        },
                        new
                        {
                            TipoMedicacaoId = 5,
                            ClasseAplicacao = 2,
                            DescMedicacao = "Aplicada diretamente no músculo",
                            TituloTipoMedicacao = "Intramuscular"
                        },
                        new
                        {
                            TipoMedicacaoId = 6,
                            ClasseAplicacao = 2,
                            DescMedicacao = "Aplicada debaixo da pele",
                            TituloTipoMedicacao = "Subcutânea"
                        },
                        new
                        {
                            TipoMedicacaoId = 7,
                            ClasseAplicacao = 2,
                            DescMedicacao = "",
                            TituloTipoMedicacao = "Respiratória"
                        },
                        new
                        {
                            TipoMedicacaoId = 8,
                            ClasseAplicacao = 2,
                            DescMedicacao = "Aplicada por pomadas",
                            TituloTipoMedicacao = "Via tópica"
                        },
                        new
                        {
                            TipoMedicacaoId = 9,
                            ClasseAplicacao = 2,
                            DescMedicacao = "",
                            TituloTipoMedicacao = "Via Ocular"
                        },
                        new
                        {
                            TipoMedicacaoId = 10,
                            ClasseAplicacao = 2,
                            DescMedicacao = "",
                            TituloTipoMedicacao = "Via Nasal"
                        },
                        new
                        {
                            TipoMedicacaoId = 11,
                            ClasseAplicacao = 2,
                            DescMedicacao = "",
                            TituloTipoMedicacao = "Via Auricular"
                        });
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.Pacientes.CuidadorPaciente", b =>
                {
                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.Property<int>("CuidadorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("DATETIME2(0)");

                    b.Property<DateTime>("FinalizadoEm")
                        .HasColumnType("DATETIME2(0)");

                    b.HasKey("PacienteId", "CuidadorId")
                        .HasName("PK_CuidadorPacientes_PacienteId_CuidadorId");

                    b.HasIndex("CuidadorId");

                    b.ToTable("CuidadorPacientes");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.Pacientes.GrauParentesco", b =>
                {
                    b.Property<int>("GrauParentescoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GrauParentescoId"));

                    b.Property<string>("DescGrauParentesco")
                        .IsRequired()
                        .HasColumnType("VARCHAR(15)");

                    b.HasKey("GrauParentescoId")
                        .HasName("PK_GrauParentescoId");

                    b.ToTable("GrauParentesco");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.Pacientes.ObservacaoPaciente", b =>
                {
                    b.Property<int>("SqObservacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SqObservacao"));

                    b.Property<DateTime>("MtObservacao")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.HasKey("SqObservacao")
                        .HasName("PK_SqObservacao");

                    b.HasIndex("PacienteId");

                    b.ToTable("ObservacoesPacientes");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.Pacientes.ResponsavelPaciente", b =>
                {
                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.Property<int>("ResponsavelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("GrauParentescoId")
                        .HasColumnType("int");

                    b.HasKey("PacienteId", "ResponsavelId")
                        .HasName("PK_PacienteId_ResponsavelId");

                    b.HasIndex("GrauParentescoId")
                        .IsUnique();

                    b.HasIndex("ResponsavelId");

                    b.ToTable("ResponsaveisPacientes");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.Pessoas.ContatoPessoa", b =>
                {
                    b.Property<int>("PessoaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnType("CHAR(11)");

                    b.Property<string>("CelularSecundario")
                        .HasColumnType("CHAR(11)");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Telefone")
                        .HasColumnType("CHAR(10)");

                    b.Property<string>("TelefoneSecundario")
                        .HasColumnType("CHAR(10)");

                    b.HasKey("PessoaId")
                        .HasName("PK_ContatoPessoaId");

                    b.HasIndex("Celular");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("ContatoPessoas");

                    b.HasData(
                        new
                        {
                            PessoaId = 1,
                            Celular = "11978486810",
                            CriadoEm = new DateTime(2023, 4, 6, 23, 0, 51, 876, DateTimeKind.Local).AddTicks(6807),
                            Email = "user@user.com"
                        });
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.Pessoas.EnderecoPessoa", b =>
                {
                    b.Property<int>("PessoaId")
                        .HasColumnType("int");

                    b.Property<string>("BairroLogradouro")
                        .IsRequired()
                        .HasColumnType("VARCHAR(25)");

                    b.Property<string>("CEPEndereco")
                        .IsRequired()
                        .HasColumnType("CHAR(8)");

                    b.Property<string>("CidadeEndereco")
                        .IsRequired()
                        .HasColumnType("VARCHAR(25)");

                    b.Property<string>("Complemento")
                        .HasColumnType("VARCHAR(15)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("VARCHAR(40)");

                    b.Property<int>("NroLogradouro")
                        .HasColumnType("INT");

                    b.Property<string>("UFEndereco")
                        .IsRequired()
                        .HasColumnType("CHAR(2)");

                    b.HasKey("PessoaId")
                        .HasName("PK_FK_EnderecoPessoa");

                    b.ToTable("EnderecoPessoas");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.Pessoas.Pessoa", b =>
                {
                    b.Property<int>("PessoaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PessoaId"));

                    b.Property<string>("CpfPessoa")
                        .IsRequired()
                        .HasColumnType("CHAR(11)");

                    b.Property<DateTime>("DtNascPessoa")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("NomePessoa")
                        .IsRequired()
                        .HasColumnType("VARCHAR(25)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("SobreNomePessoa")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)");

                    b.Property<int>("TipoPessoa")
                        .HasColumnType("int");

                    b.HasKey("PessoaId")
                        .HasName("PK_PessoaId");

                    b.HasIndex("CpfPessoa")
                        .IsUnique();

                    b.ToTable("Pessoas");

                    b.HasData(
                        new
                        {
                            PessoaId = 1,
                            CpfPessoa = "67146867064",
                            DtNascPessoa = new DateTime(2004, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NomePessoa = "Dan",
                            PasswordHash = new byte[] { 50, 98, 169, 16, 36, 8, 146, 18, 76, 82, 219, 106, 72, 245, 7, 179, 191, 240, 45, 92, 187, 46, 233, 201, 65, 182, 101, 254, 63, 16, 145, 219, 187, 73, 91, 19, 36, 68, 99, 219, 153, 231, 58, 19, 222, 22, 28, 150, 248, 77, 91, 47, 143, 34, 212, 217, 175, 48, 64, 206, 20, 179, 50, 132 },
                            PasswordSalt = new byte[] { 67, 137, 26, 205, 136, 169, 247, 135, 232, 182, 25, 228, 212, 65, 206, 199, 221, 55, 97, 133, 88, 30, 106, 10, 133, 226, 102, 47, 78, 18, 30, 139, 225, 93, 207, 63, 149, 155, 46, 121, 177, 108, 91, 211, 234, 93, 148, 221, 233, 250, 153, 81, 201, 182, 111, 121, 230, 72, 228, 150, 163, 239, 241, 177, 127, 104, 12, 77, 22, 205, 188, 250, 233, 169, 147, 5, 227, 189, 37, 187, 46, 60, 44, 164, 100, 38, 95, 105, 143, 52, 138, 181, 25, 245, 57, 255, 139, 88, 220, 252, 246, 10, 44, 176, 58, 50, 248, 39, 106, 220, 61, 26, 207, 112, 65, 107, 70, 210, 197, 102, 118, 124, 218, 13, 203, 153, 152, 35 },
                            SobreNomePessoa = "Marzo",
                            TipoPessoa = 3
                        },
                        new
                        {
                            PessoaId = 2,
                            CpfPessoa = "15063626050",
                            DtNascPessoa = new DateTime(2004, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NomePessoa = "Dan PACIENTE INCAPAZ",
                            PasswordHash = new byte[] { 50, 98, 169, 16, 36, 8, 146, 18, 76, 82, 219, 106, 72, 245, 7, 179, 191, 240, 45, 92, 187, 46, 233, 201, 65, 182, 101, 254, 63, 16, 145, 219, 187, 73, 91, 19, 36, 68, 99, 219, 153, 231, 58, 19, 222, 22, 28, 150, 248, 77, 91, 47, 143, 34, 212, 217, 175, 48, 64, 206, 20, 179, 50, 132 },
                            PasswordSalt = new byte[] { 67, 137, 26, 205, 136, 169, 247, 135, 232, 182, 25, 228, 212, 65, 206, 199, 221, 55, 97, 133, 88, 30, 106, 10, 133, 226, 102, 47, 78, 18, 30, 139, 225, 93, 207, 63, 149, 155, 46, 121, 177, 108, 91, 211, 234, 93, 148, 221, 233, 250, 153, 81, 201, 182, 111, 121, 230, 72, 228, 150, 163, 239, 241, 177, 127, 104, 12, 77, 22, 205, 188, 250, 233, 169, 147, 5, 227, 189, 37, 187, 46, 60, 44, 164, 100, 38, 95, 105, 143, 52, 138, 181, 25, 245, 57, 255, 139, 88, 220, 252, 246, 10, 44, 176, 58, 50, 248, 39, 106, 220, 61, 26, 207, 112, 65, 107, 70, 210, 197, 102, 118, 124, 218, 13, 203, 153, 152, 35 },
                            SobreNomePessoa = "Marzo",
                            TipoPessoa = 2
                        });
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.ConsultasMedicas.ConsultaAgendada", b =>
                {
                    b.HasOne("WEB_API_HealTime.Models.ConsultasMedicas.Especialidade", "Especialidade")
                        .WithMany("ConsultaAgendadas")
                        .HasForeignKey("EspecialidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EspecialidadeId");

                    b.HasOne("WEB_API_HealTime.Models.ConsultasMedicas.Medico", "Medico")
                        .WithMany("ConsultaAgendadas")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MedicoId_ConsultaAgendadaId");

                    b.HasOne("WEB_API_HealTime.Models.ConsultasMedicas.StatusConsulta", "StatusConsulta")
                        .WithMany("ConsultasAgendadas")
                        .HasForeignKey("StatusConsultaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ConsultaAgendadas_StatusConsulta");

                    b.Navigation("Especialidade");

                    b.Navigation("Medico");

                    b.Navigation("StatusConsulta");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.ConsultasMedicas.ConsultaCancelada", b =>
                {
                    b.HasOne("WEB_API_HealTime.Models.ConsultasMedicas.ConsultaAgendada", "ConsultaAgendada")
                        .WithOne("ConsultaCancelada")
                        .HasForeignKey("WEB_API_HealTime.Models.ConsultasMedicas.ConsultaCancelada", "ConsultaAgendadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ConsultaAgendadaId");

                    b.Navigation("ConsultaAgendada");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.Medicacoes.AndamentoMedicacao", b =>
                {
                    b.HasOne("WEB_API_HealTime.Models.Medicacoes.PrescricaoPaciente", "PrescricaoPacientes")
                        .WithMany("AndamentoMedicacoes")
                        .HasForeignKey("MedicacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PrescricaoPaciente_MedicacaoId_AndamentoMedicacoes");

                    b.Navigation("PrescricaoPacientes");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.Medicacoes.Medicacao", b =>
                {
                    b.HasOne("WEB_API_HealTime.Models.Medicacoes.TipoMedicacao", "TipoMedicacao")
                        .WithMany("Medicacoes")
                        .HasForeignKey("TipoMedicacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Medicacao_TipoMedicacao");

                    b.Navigation("TipoMedicacao");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.Medicacoes.PrescricaoMedicacao", b =>
                {
                    b.HasOne("WEB_API_HealTime.Models.Medicacoes.Medicacao", "Medicacao")
                        .WithOne("PrescricaoMedicacao")
                        .HasForeignKey("WEB_API_HealTime.Models.Medicacoes.PrescricaoMedicacao", "MedicacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("PK_MedicacaoId_PrescricaoMedicao");

                    b.HasOne("WEB_API_HealTime.Models.Medicacoes.PrescricaoPaciente", "PrescricaoPaciente")
                        .WithMany("PrescricoesMedicacoes")
                        .HasForeignKey("PrescricaoPacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("PK_PrescricaoPacienteId_PrescricaoMedicao");

                    b.Navigation("Medicacao");

                    b.Navigation("PrescricaoPaciente");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.Medicacoes.PrescricaoPaciente", b =>
                {
                    b.HasOne("WEB_API_HealTime.Models.ConsultasMedicas.Medico", "Medico")
                        .WithMany("PrescricoesPacientes")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PrescricaoPaciente_Medico");

                    b.HasOne("WEB_API_HealTime.Models.Pessoas.Pessoa", "Pessoa")
                        .WithMany("PrescricaoPacientes")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PacienteId_PrescricoesPacientes");

                    b.Navigation("Medico");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.Pacientes.CuidadorPaciente", b =>
                {
                    b.HasOne("WEB_API_HealTime.Models.Pessoas.Pessoa", "PessoaCuidador")
                        .WithMany("CuidadorPaciente_Cuidador")
                        .HasForeignKey("CuidadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Pessoa_CuidadorPaciente_CuidadorId");

                    b.HasOne("WEB_API_HealTime.Models.Pessoas.Pessoa", "PessoaPaciente")
                        .WithMany("CuidadorPaciente_Pacientes")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Pessoa_CuidadorPaciente_PacienteId");

                    b.Navigation("PessoaCuidador");

                    b.Navigation("PessoaPaciente");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.Pacientes.ObservacaoPaciente", b =>
                {
                    b.HasOne("WEB_API_HealTime.Models.Pessoas.Pessoa", "Paciente")
                        .WithMany("ObservacoesPacientes")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SqObservacao_Pessoas");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.Pacientes.ResponsavelPaciente", b =>
                {
                    b.HasOne("WEB_API_HealTime.Models.Pacientes.GrauParentesco", "GrauParentesco")
                        .WithOne("ResponsavelPaciente")
                        .HasForeignKey("WEB_API_HealTime.Models.Pacientes.ResponsavelPaciente", "GrauParentescoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GrauParentescoId_GrauParentesco_ResponsavelPaciente");

                    b.HasOne("WEB_API_HealTime.Models.Pessoas.Pessoa", "Paciente")
                        .WithMany("ResponsavelPacientes_Pacientes")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PacienteId_Pessoas_ResponsavelPaciente");

                    b.HasOne("WEB_API_HealTime.Models.Pessoas.Pessoa", "Responsavel")
                        .WithMany("ResponsavelPacientes_Responsaveis")
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ResponsavelId_Pessoas_ResponsavelPaciente");

                    b.Navigation("GrauParentesco");

                    b.Navigation("Paciente");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.Pessoas.ContatoPessoa", b =>
                {
                    b.HasOne("WEB_API_HealTime.Models.Pessoas.Pessoa", "Pessoa")
                        .WithOne("ContatoPessoa")
                        .HasForeignKey("WEB_API_HealTime.Models.Pessoas.ContatoPessoa", "PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Pessoa_ContatoPessoa_PessoaId");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.Pessoas.EnderecoPessoa", b =>
                {
                    b.HasOne("WEB_API_HealTime.Models.Pessoas.Pessoa", "Pessoa")
                        .WithOne("EnderecoPessoa")
                        .HasForeignKey("WEB_API_HealTime.Models.Pessoas.EnderecoPessoa", "PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PK_EnderecoPessoa");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.ConsultasMedicas.ConsultaAgendada", b =>
                {
                    b.Navigation("ConsultaCancelada");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.ConsultasMedicas.Especialidade", b =>
                {
                    b.Navigation("ConsultaAgendadas");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.ConsultasMedicas.Medico", b =>
                {
                    b.Navigation("ConsultaAgendadas");

                    b.Navigation("PrescricoesPacientes");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.ConsultasMedicas.StatusConsulta", b =>
                {
                    b.Navigation("ConsultasAgendadas");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.Medicacoes.Medicacao", b =>
                {
                    b.Navigation("PrescricaoMedicacao");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.Medicacoes.PrescricaoPaciente", b =>
                {
                    b.Navigation("AndamentoMedicacoes");

                    b.Navigation("PrescricoesMedicacoes");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.Medicacoes.TipoMedicacao", b =>
                {
                    b.Navigation("Medicacoes");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.Pacientes.GrauParentesco", b =>
                {
                    b.Navigation("ResponsavelPaciente");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.Pessoas.Pessoa", b =>
                {
                    b.Navigation("ContatoPessoa");

                    b.Navigation("CuidadorPaciente_Cuidador");

                    b.Navigation("CuidadorPaciente_Pacientes");

                    b.Navigation("EnderecoPessoa");

                    b.Navigation("ObservacoesPacientes");

                    b.Navigation("PrescricaoPacientes");

                    b.Navigation("ResponsavelPacientes_Pacientes");

                    b.Navigation("ResponsavelPacientes_Responsaveis");
                });
#pragma warning restore 612, 618
        }
    }
}
