// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WEB_API_HealTime.Data;

#nullable disable

namespace WEB_API_HealTime.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WEB_API_HealTime.Models.ConsultasMedicas.ConsultaAgendada", b =>
                {
                    b.Property<int>("ConsultasAgendadasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsultasAgendadasId"));

                    b.Property<DateTime>("DataConsulta")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("DataSolicitacaoConsulta")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Encaminhamento")
                        .IsRequired()
                        .HasColumnType("CHAR(1)");

                    b.Property<int>("EspecialidadeId")
                        .HasColumnType("int");

                    b.Property<int>("MedicoId")
                        .HasColumnType("int");

                    b.Property<string>("MotivoConsulta")
                        .HasColumnType("VARCHAR(300)");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.Property<int>("StatusConsultaId")
                        .HasColumnType("int");

                    b.HasKey("ConsultasAgendadasId")
                        .HasName("PK_ConsultaAgendadaId");

                    b.HasIndex("EspecialidadeId");

                    b.HasIndex("MedicoId");

                    b.HasIndex("StatusConsultaId");

                    b.ToTable("ConsultasAgendadas");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.ConsultasMedicas.ConsultaCancelada", b =>
                {
                    b.Property<int>("ConsultaCanceladaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConsultaCanceladaId"));

                    b.Property<int>("ConsultaAgendadaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCancelamento")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("MotivoCancelamento")
                        .IsRequired()
                        .HasColumnType("VARCHAR(300)");

                    b.HasKey("ConsultaCanceladaId", "ConsultaAgendadaId")
                        .HasName("PK_ConsultaCancelada_ConsultaAgendada");

                    b.HasIndex("ConsultaAgendadaId")
                        .IsUnique();

                    b.ToTable("ConsultaCanceladas");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.ConsultasMedicas.Especialidade", b =>
                {
                    b.Property<int>("EspecialidadeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EspecialidadeId"));

                    b.Property<string>("DescEspecialidade")
                        .IsRequired()
                        .HasColumnType("VARCHAR(25)");

                    b.HasKey("EspecialidadeId")
                        .HasName("PK_EspecialidadeId");

                    b.ToTable("Especialidades");

                    b.HasData(
                        new
                        {
                            EspecialidadeId = 1,
                            DescEspecialidade = "Cardiologia"
                        },
                        new
                        {
                            EspecialidadeId = 2,
                            DescEspecialidade = "Dermatologia"
                        },
                        new
                        {
                            EspecialidadeId = 3,
                            DescEspecialidade = "Ginecologia/Obstetrícia"
                        },
                        new
                        {
                            EspecialidadeId = 4,
                            DescEspecialidade = "Ortopedia"
                        },
                        new
                        {
                            EspecialidadeId = 5,
                            DescEspecialidade = "Anestesiologia"
                        },
                        new
                        {
                            EspecialidadeId = 6,
                            DescEspecialidade = "Pediatria"
                        },
                        new
                        {
                            EspecialidadeId = 7,
                            DescEspecialidade = "Oftalmologia"
                        },
                        new
                        {
                            EspecialidadeId = 8,
                            DescEspecialidade = "Psiquiatria"
                        },
                        new
                        {
                            EspecialidadeId = 9,
                            DescEspecialidade = "Urologia"
                        },
                        new
                        {
                            EspecialidadeId = 10,
                            DescEspecialidade = "Oncologia"
                        },
                        new
                        {
                            EspecialidadeId = 11,
                            DescEspecialidade = "Endocrinologia"
                        },
                        new
                        {
                            EspecialidadeId = 12,
                            DescEspecialidade = "Neurologia"
                        },
                        new
                        {
                            EspecialidadeId = 13,
                            DescEspecialidade = "Hematologia"
                        },
                        new
                        {
                            EspecialidadeId = 14,
                            DescEspecialidade = "Cirurgia Plástica"
                        });
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.ConsultasMedicas.Medico", b =>
                {
                    b.Property<int>("MedicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicoId"));

                    b.Property<string>("CrmMedico")
                        .HasColumnType("CHAR(6)");

                    b.Property<string>("NmMedico")
                        .IsRequired()
                        .HasColumnType("VARCHAR(40)");

                    b.Property<string>("UfCrmMedico")
                        .IsRequired()
                        .HasColumnType("CHAR(2)");

                    b.HasKey("MedicoId")
                        .HasName("PK_MedicoId");

                    b.ToTable("Medicos");

                    b.HasData(
                        new
                        {
                            MedicoId = 1,
                            CrmMedico = "054321",
                            NmMedico = "Dr Guilherme Costa",
                            UfCrmMedico = "SP"
                        },
                        new
                        {
                            MedicoId = 2,
                            CrmMedico = "012345",
                            NmMedico = "Dr Adriana Gomes",
                            UfCrmMedico = "RJ"
                        });
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.ConsultasMedicas.StatusConsulta", b =>
                {
                    b.Property<int>("StatusConsultaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusConsultaId"));

                    b.Property<string>("DescStatusConsulta")
                        .IsRequired()
                        .HasColumnType("VARCHAR(25)");

                    b.HasKey("StatusConsultaId")
                        .HasName("PK_StatusConsultaId");

                    b.ToTable("StatusConsultas");

                    b.HasData(
                        new
                        {
                            StatusConsultaId = 1,
                            DescStatusConsulta = "Agendada"
                        },
                        new
                        {
                            StatusConsultaId = 2,
                            DescStatusConsulta = "Encerrada"
                        },
                        new
                        {
                            StatusConsultaId = 3,
                            DescStatusConsulta = "Cancelada"
                        },
                        new
                        {
                            StatusConsultaId = 4,
                            DescStatusConsulta = "Remarcada"
                        },
                        new
                        {
                            StatusConsultaId = 5,
                            DescStatusConsulta = "Fila de espera"
                        });
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.Medicacoes.AndamentoMedicacao", b =>
                {
                    b.Property<int>("AndamentoMedicacaoId")
                        .HasColumnType("int");

                    b.Property<int>("PrescricaoMedicacaoId")
                        .HasColumnType("INT");

                    b.Property<int>("MedicacaoId")
                        .HasColumnType("int");

                    b.Property<int>("PrescricaoPacienteId")
                        .HasColumnType("int");

                    b.Property<bool>("BaixaAndamentoMedicacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("CodAplicadorMedicacao")
                        .HasColumnType("INT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("MtAndamentoMedicacao")
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime?>("MtBaixaMedicacao")
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("QtdeMedicao")
                        .HasColumnType("INT");

                    b.HasKey("AndamentoMedicacaoId", "PrescricaoMedicacaoId", "MedicacaoId", "PrescricaoPacienteId")
                        .HasName("PK_AndamentoMedicacao_AndamentoMedicacaoId");

                    b.HasIndex("PrescricaoMedicacaoId");

                    b.HasIndex("PrescricaoPacienteId");

                    b.ToTable("AndamentoMedicacoes", t =>
                        {
                            t.HasTrigger("ControlStatePrescriptionMedicine");
                        });
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.Medicacoes.Medicacao", b =>
                {
                    b.Property<int>("MedicacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicacaoId"));

                    b.Property<int>("CodPessoaAlter")
                        .HasColumnType("int");

                    b.Property<string>("CompostoAtivoMedicacao")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<string>("Generico")
                        .IsRequired()
                        .HasColumnType("CHAR(1)");

                    b.Property<string>("LaboratorioMedicacao")
                        .IsRequired()
                        .HasColumnType("VARCHAR(80)");

                    b.Property<string>("NomeMedicacao")
                        .IsRequired()
                        .HasColumnType("VARCHAR(80)");

                    b.Property<int>("StatusMedicacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("TipoMedicacaoId")
                        .HasColumnType("int");

                    b.HasKey("MedicacaoId")
                        .HasName("PK_MedicacaoId");

                    b.HasIndex("TipoMedicacaoId");

                    b.ToTable("Medicacoes");

                    b.HasData(
                        new
                        {
                            MedicacaoId = 1,
                            CodPessoaAlter = 0,
                            CompostoAtivoMedicacao = "pirazolônico não narcótico ",
                            Generico = "S",
                            LaboratorioMedicacao = "Sanofi-Aventis",
                            NomeMedicacao = "DIPIRONA 80g",
                            StatusMedicacao = 1,
                            TipoMedicacaoId = 1
                        },
                        new
                        {
                            MedicacaoId = 2,
                            CodPessoaAlter = 0,
                            CompostoAtivoMedicacao = "ceftriaxona",
                            Generico = "S",
                            LaboratorioMedicacao = "Roche",
                            NomeMedicacao = "Rocefin",
                            StatusMedicacao = 1,
                            TipoMedicacaoId = 2
                        });
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.Medicacoes.PrescricaoMedicacao", b =>
                {
                    b.Property<int>("PrescricaoMedicacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrescricaoMedicacaoId"));

                    b.Property<int>("Duracao")
                        .HasColumnType("int");

                    b.Property<bool>("HorariosDefinidos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<TimeSpan>("Intervalo")
                        .HasColumnType("TIME");

                    b.Property<int>("MedicacaoId")
                        .HasColumnType("int");

                    b.Property<int>("PrescricaoPacienteId")
                        .HasColumnType("int");

                    b.Property<double>("Qtde")
                        .HasColumnType("FLOAT(10, 2)");

                    b.Property<bool>("StatusMedicacaoFlag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("PrescricaoMedicacaoId")
                        .HasName("PK__PrescricaPacienteId");

                    b.HasIndex("MedicacaoId");

                    b.HasIndex("PrescricaoPacienteId");

                    b.ToTable("PrescricoesMedicacoes");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.Medicacoes.PrescricaoPaciente", b =>
                {
                    b.Property<int>("PrescricaoPacienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrescricaoPacienteId"));

                    b.Property<DateTime?>("CriadoEm")
                        .IsRequired()
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("DescFichaPessoa")
                        .HasColumnType("VARCHAR(350)");

                    b.Property<DateTime>("Emissao")
                        .HasColumnType("datetime2(0)");

                    b.Property<bool>("FlagStatusAtivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("MedicoId")
                        .HasColumnType("int");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Validade")
                        .HasColumnType("datetime2(0)");

                    b.HasKey("PrescricaoPacienteId")
                        .HasName("PK_PrescricaoPacienteId");

                    b.HasIndex("MedicoId");

                    b.HasIndex("PacienteId");

                    b.ToTable("PrescricaoPacientes");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.Medicacoes.TipoMedicacao", b =>
                {
                    b.Property<int>("TipoMedicacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoMedicacaoId"));

                    b.Property<int>("ClasseAplicacao")
                        .HasColumnType("int");

                    b.Property<string>("DescMedicacao")
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("TituloTipoMedicacao")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.HasKey("TipoMedicacaoId")
                        .HasName("PK_TipoMedicacaoId");

                    b.ToTable("TiposMedicacoes");

                    b.HasData(
                        new
                        {
                            TipoMedicacaoId = 1,
                            ClasseAplicacao = 1,
                            DescMedicacao = "Aplicado pela boca",
                            TituloTipoMedicacao = "Via oral"
                        },
                        new
                        {
                            TipoMedicacaoId = 2,
                            ClasseAplicacao = 1,
                            DescMedicacao = "Aplicado  por dembaixo da língua",
                            TituloTipoMedicacao = "Sublingual"
                        },
                        new
                        {
                            TipoMedicacaoId = 3,
                            ClasseAplicacao = 1,
                            DescMedicacao = "Aplicado pelo canal retal",
                            TituloTipoMedicacao = "Supositorios"
                        },
                        new
                        {
                            TipoMedicacaoId = 4,
                            ClasseAplicacao = 2,
                            DescMedicacao = "Aplicada diretamente no sangue",
                            TituloTipoMedicacao = "Intravenosa"
                        },
                        new
                        {
                            TipoMedicacaoId = 5,
                            ClasseAplicacao = 2,
                            DescMedicacao = "Aplicada diretamente no músculo",
                            TituloTipoMedicacao = "Intramuscular"
                        },
                        new
                        {
                            TipoMedicacaoId = 6,
                            ClasseAplicacao = 2,
                            DescMedicacao = "Aplicada debaixo da pele",
                            TituloTipoMedicacao = "Subcutânea"
                        },
                        new
                        {
                            TipoMedicacaoId = 7,
                            ClasseAplicacao = 2,
                            DescMedicacao = "",
                            TituloTipoMedicacao = "Respiratória"
                        },
                        new
                        {
                            TipoMedicacaoId = 8,
                            ClasseAplicacao = 2,
                            DescMedicacao = "Aplicada por pomadas",
                            TituloTipoMedicacao = "Via tópica"
                        },
                        new
                        {
                            TipoMedicacaoId = 9,
                            ClasseAplicacao = 2,
                            DescMedicacao = "",
                            TituloTipoMedicacao = "Via Ocular"
                        },
                        new
                        {
                            TipoMedicacaoId = 10,
                            ClasseAplicacao = 2,
                            DescMedicacao = "",
                            TituloTipoMedicacao = "Via Nasal"
                        },
                        new
                        {
                            TipoMedicacaoId = 11,
                            ClasseAplicacao = 2,
                            DescMedicacao = "",
                            TituloTipoMedicacao = "Via Auricular"
                        });
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.Pacientes.CuidadorPaciente", b =>
                {
                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.Property<int>("CuidadorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("DATETIME2(0)");

                    b.Property<DateTime?>("FinalizadoEm")
                        .HasColumnType("DATETIME2(0)");

                    b.HasKey("PacienteId", "CuidadorId", "CriadoEm")
                        .HasName("PK_CuidadorPacientes_PacienteId_CuidadorId");

                    b.HasIndex("CuidadorId");

                    b.ToTable("CuidadorPacientes");

                    b.HasData(
                        new
                        {
                            PacienteId = 4,
                            CuidadorId = 2,
                            CriadoEm = new DateTime(2023, 6, 20, 20, 0, 11, 487, DateTimeKind.Local).AddTicks(68)
                        },
                        new
                        {
                            PacienteId = 5,
                            CuidadorId = 2,
                            CriadoEm = new DateTime(2023, 6, 20, 20, 0, 11, 487, DateTimeKind.Local).AddTicks(69)
                        },
                        new
                        {
                            PacienteId = 6,
                            CuidadorId = 2,
                            CriadoEm = new DateTime(2023, 6, 20, 20, 0, 11, 487, DateTimeKind.Local).AddTicks(70)
                        });
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.Pacientes.GrauParentesco", b =>
                {
                    b.Property<int>("GrauParentescoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GrauParentescoId"));

                    b.Property<string>("DescGrauParentesco")
                        .IsRequired()
                        .HasColumnType("VARCHAR(15)");

                    b.HasKey("GrauParentescoId")
                        .HasName("PK_GrauParentescoId");

                    b.ToTable("GrauParentesco");

                    b.HasData(
                        new
                        {
                            GrauParentescoId = 1,
                            DescGrauParentesco = "Mãe"
                        },
                        new
                        {
                            GrauParentescoId = 2,
                            DescGrauParentesco = "Pai"
                        },
                        new
                        {
                            GrauParentescoId = 3,
                            DescGrauParentesco = "Filha/Filho"
                        },
                        new
                        {
                            GrauParentescoId = 4,
                            DescGrauParentesco = "Esposa"
                        },
                        new
                        {
                            GrauParentescoId = 5,
                            DescGrauParentesco = "Marido"
                        });
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.Pacientes.ObservacaoPaciente", b =>
                {
                    b.Property<int>("SqObservacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SqObservacao"));

                    b.Property<DateTime>("MtObservacao")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.HasKey("SqObservacao")
                        .HasName("PK_SqObservacao");

                    b.HasIndex("PacienteId");

                    b.ToTable("ObservacoesPacientes");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.Pacientes.ResponsavelPaciente", b =>
                {
                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.Property<int>("ResponsavelId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("GrauParentescoId")
                        .HasColumnType("int");

                    b.HasKey("PacienteId", "ResponsavelId")
                        .HasName("PK_PacienteId_ResponsavelId");

                    b.HasIndex("GrauParentescoId");

                    b.HasIndex("ResponsavelId");

                    b.ToTable("ResponsaveisPacientes");

                    b.HasData(
                        new
                        {
                            PacienteId = 4,
                            ResponsavelId = 1,
                            CriadoEm = new DateTime(2023, 6, 20, 20, 0, 11, 487, DateTimeKind.Local).AddTicks(91),
                            GrauParentescoId = 1
                        },
                        new
                        {
                            PacienteId = 5,
                            ResponsavelId = 1,
                            CriadoEm = new DateTime(2023, 6, 20, 20, 0, 11, 487, DateTimeKind.Local).AddTicks(93),
                            GrauParentescoId = 3
                        });
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.Pessoas.ContatoPessoa", b =>
                {
                    b.Property<int>("PessoaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("datetime2");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnType("CHAR(11)");

                    b.Property<string>("CelularSecundario")
                        .HasColumnType("CHAR(11)");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("VARCHAR(100)");

                    b.Property<string>("Telefone")
                        .HasColumnType("CHAR(10)");

                    b.Property<string>("TelefoneSecundario")
                        .HasColumnType("CHAR(10)");

                    b.HasKey("PessoaId")
                        .HasName("PK_ContatoPessoaId");

                    b.HasIndex("Celular");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("ContatoPessoas");

                    b.HasData(
                        new
                        {
                            PessoaId = 1,
                            Celular = "11978486810",
                            CriadoEm = new DateTime(2023, 6, 20, 20, 0, 11, 487, DateTimeKind.Local).AddTicks(40),
                            Email = "may@may.com"
                        },
                        new
                        {
                            PessoaId = 2,
                            Celular = "11978486810",
                            CriadoEm = new DateTime(2023, 6, 20, 20, 0, 11, 487, DateTimeKind.Local).AddTicks(49),
                            Email = "thi@thi.com"
                        },
                        new
                        {
                            PessoaId = 3,
                            Celular = "11978486810",
                            CriadoEm = new DateTime(2023, 6, 20, 20, 0, 11, 487, DateTimeKind.Local).AddTicks(50),
                            Email = "dan@dan.com"
                        });
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.Pessoas.EnderecoPessoa", b =>
                {
                    b.Property<int>("PessoaId")
                        .HasColumnType("int");

                    b.Property<string>("BairroLogradouro")
                        .IsRequired()
                        .HasColumnType("VARCHAR(25)");

                    b.Property<string>("CEPEndereco")
                        .IsRequired()
                        .HasColumnType("CHAR(8)");

                    b.Property<string>("CidadeEndereco")
                        .IsRequired()
                        .HasColumnType("VARCHAR(25)");

                    b.Property<string>("Complemento")
                        .HasColumnType("VARCHAR(15)");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("VARCHAR(40)");

                    b.Property<int>("NroLogradouro")
                        .HasColumnType("INT");

                    b.Property<string>("UFEndereco")
                        .IsRequired()
                        .HasColumnType("CHAR(2)");

                    b.HasKey("PessoaId")
                        .HasName("PK_FK_EnderecoPessoa");

                    b.ToTable("EnderecoPessoas");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.Pessoas.Pessoa", b =>
                {
                    b.Property<int>("PessoaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PessoaId"));

                    b.Property<string>("CpfPessoa")
                        .IsRequired()
                        .HasColumnType("CHAR(11)");

                    b.Property<DateTime>("DtNascPessoa")
                        .HasColumnType("datetime2(0)");

                    b.Property<byte[]>("FotoUsuario")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("NomePessoa")
                        .IsRequired()
                        .HasColumnType("VARCHAR(25)");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("SobreNomePessoa")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)");

                    b.Property<int>("TipoPessoa")
                        .HasColumnType("int");

                    b.HasKey("PessoaId")
                        .HasName("PK_PessoaId");

                    b.HasIndex("CpfPessoa")
                        .IsUnique()
                        .HasDatabaseName("UNIQUE_ON_CPF");

                    b.ToTable("Pessoas");

                    b.HasData(
                        new
                        {
                            PessoaId = 1,
                            CpfPessoa = "67146867064",
                            DtNascPessoa = new DateTime(2003, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NomePessoa = "Mayara",
                            PasswordHash = new byte[] { 132, 93, 193, 19, 129, 161, 139, 122, 241, 175, 161, 151, 127, 224, 150, 165, 115, 126, 226, 222, 241, 29, 13, 115, 121, 138, 130, 89, 186, 103, 241, 131, 49, 186, 21, 45, 161, 157, 110, 95, 88, 111, 125, 241, 11, 143, 161, 116, 248, 26, 64, 155, 85, 17, 115, 185, 194, 186, 135, 253, 51, 240, 220, 115 },
                            PasswordSalt = new byte[] { 207, 159, 49, 21, 202, 191, 203, 158, 132, 46, 8, 190, 144, 185, 157, 254, 64, 118, 75, 4, 144, 81, 62, 110, 1, 217, 35, 235, 179, 228, 92, 46, 155, 255, 182, 83, 88, 138, 66, 221, 103, 172, 5, 8, 22, 181, 158, 17, 201, 122, 124, 127, 182, 158, 72, 9, 90, 69, 192, 126, 93, 22, 37, 168, 66, 167, 27, 76, 208, 89, 252, 240, 186, 131, 31, 97, 194, 23, 18, 42, 190, 129, 18, 165, 173, 24, 12, 226, 207, 37, 5, 207, 9, 233, 239, 71, 200, 143, 192, 62, 68, 167, 121, 38, 218, 166, 83, 137, 53, 188, 18, 3, 143, 5, 30, 104, 240, 247, 118, 48, 159, 102, 250, 111, 200, 217, 97, 253 },
                            SobreNomePessoa = "Pilecarte",
                            TipoPessoa = 3
                        },
                        new
                        {
                            PessoaId = 2,
                            CpfPessoa = "94840911053",
                            DtNascPessoa = new DateTime(2003, 7, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NomePessoa = "Thiago",
                            PasswordHash = new byte[] { 132, 93, 193, 19, 129, 161, 139, 122, 241, 175, 161, 151, 127, 224, 150, 165, 115, 126, 226, 222, 241, 29, 13, 115, 121, 138, 130, 89, 186, 103, 241, 131, 49, 186, 21, 45, 161, 157, 110, 95, 88, 111, 125, 241, 11, 143, 161, 116, 248, 26, 64, 155, 85, 17, 115, 185, 194, 186, 135, 253, 51, 240, 220, 115 },
                            PasswordSalt = new byte[] { 207, 159, 49, 21, 202, 191, 203, 158, 132, 46, 8, 190, 144, 185, 157, 254, 64, 118, 75, 4, 144, 81, 62, 110, 1, 217, 35, 235, 179, 228, 92, 46, 155, 255, 182, 83, 88, 138, 66, 221, 103, 172, 5, 8, 22, 181, 158, 17, 201, 122, 124, 127, 182, 158, 72, 9, 90, 69, 192, 126, 93, 22, 37, 168, 66, 167, 27, 76, 208, 89, 252, 240, 186, 131, 31, 97, 194, 23, 18, 42, 190, 129, 18, 165, 173, 24, 12, 226, 207, 37, 5, 207, 9, 233, 239, 71, 200, 143, 192, 62, 68, 167, 121, 38, 218, 166, 83, 137, 53, 188, 18, 3, 143, 5, 30, 104, 240, 247, 118, 48, 159, 102, 250, 111, 200, 217, 97, 253 },
                            SobreNomePessoa = "Roque",
                            TipoPessoa = 4
                        },
                        new
                        {
                            PessoaId = 3,
                            CpfPessoa = "50967422027",
                            DtNascPessoa = new DateTime(2004, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NomePessoa = "Dan",
                            PasswordHash = new byte[] { 132, 93, 193, 19, 129, 161, 139, 122, 241, 175, 161, 151, 127, 224, 150, 165, 115, 126, 226, 222, 241, 29, 13, 115, 121, 138, 130, 89, 186, 103, 241, 131, 49, 186, 21, 45, 161, 157, 110, 95, 88, 111, 125, 241, 11, 143, 161, 116, 248, 26, 64, 155, 85, 17, 115, 185, 194, 186, 135, 253, 51, 240, 220, 115 },
                            PasswordSalt = new byte[] { 207, 159, 49, 21, 202, 191, 203, 158, 132, 46, 8, 190, 144, 185, 157, 254, 64, 118, 75, 4, 144, 81, 62, 110, 1, 217, 35, 235, 179, 228, 92, 46, 155, 255, 182, 83, 88, 138, 66, 221, 103, 172, 5, 8, 22, 181, 158, 17, 201, 122, 124, 127, 182, 158, 72, 9, 90, 69, 192, 126, 93, 22, 37, 168, 66, 167, 27, 76, 208, 89, 252, 240, 186, 131, 31, 97, 194, 23, 18, 42, 190, 129, 18, 165, 173, 24, 12, 226, 207, 37, 5, 207, 9, 233, 239, 71, 200, 143, 192, 62, 68, 167, 121, 38, 218, 166, 83, 137, 53, 188, 18, 3, 143, 5, 30, 104, 240, 247, 118, 48, 159, 102, 250, 111, 200, 217, 97, 253 },
                            SobreNomePessoa = "Marzo",
                            TipoPessoa = 1
                        },
                        new
                        {
                            PessoaId = 4,
                            CpfPessoa = "15063626050",
                            DtNascPessoa = new DateTime(2004, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NomePessoa = "Nicolly",
                            SobreNomePessoa = "Sodré",
                            TipoPessoa = 2
                        },
                        new
                        {
                            PessoaId = 5,
                            CpfPessoa = "70414926056",
                            DtNascPessoa = new DateTime(2004, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NomePessoa = "Giovana",
                            SobreNomePessoa = "Silva",
                            TipoPessoa = 2
                        },
                        new
                        {
                            PessoaId = 6,
                            CpfPessoa = "46473986090",
                            DtNascPessoa = new DateTime(2004, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NomePessoa = "Pedro",
                            SobreNomePessoa = "Rocha",
                            TipoPessoa = 2
                        });
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.ConsultasMedicas.ConsultaAgendada", b =>
                {
                    b.HasOne("WEB_API_HealTime.Models.ConsultasMedicas.Especialidade", "Especialidade")
                        .WithMany("ConsultaAgendadas")
                        .HasForeignKey("EspecialidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EspecialidadeId");

                    b.HasOne("WEB_API_HealTime.Models.ConsultasMedicas.Medico", "Medico")
                        .WithMany("ConsultaAgendadas")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_MedicoId_ConsultaAgendadaId");

                    b.HasOne("WEB_API_HealTime.Models.ConsultasMedicas.StatusConsulta", "StatusConsulta")
                        .WithMany("ConsultasAgendadas")
                        .HasForeignKey("StatusConsultaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ConsultaAgendadas_StatusConsulta");

                    b.Navigation("Especialidade");

                    b.Navigation("Medico");

                    b.Navigation("StatusConsulta");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.ConsultasMedicas.ConsultaCancelada", b =>
                {
                    b.HasOne("WEB_API_HealTime.Models.ConsultasMedicas.ConsultaAgendada", "ConsultaAgendada")
                        .WithOne("ConsultaCancelada")
                        .HasForeignKey("WEB_API_HealTime.Models.ConsultasMedicas.ConsultaCancelada", "ConsultaAgendadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ConsultaAgendadaId");

                    b.Navigation("ConsultaAgendada");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.Medicacoes.AndamentoMedicacao", b =>
                {
                    b.HasOne("WEB_API_HealTime.Models.Medicacoes.PrescricaoMedicacao", "PrescricaoMedicacao")
                        .WithMany("AndamentoMedicacoes")
                        .HasForeignKey("PrescricaoMedicacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_AndamentoMedicacao_PrescricaoMedicacao");

                    b.Navigation("PrescricaoMedicacao");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.Medicacoes.Medicacao", b =>
                {
                    b.HasOne("WEB_API_HealTime.Models.Medicacoes.TipoMedicacao", "TipoMedicacao")
                        .WithMany("Medicacoes")
                        .HasForeignKey("TipoMedicacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Medicacao_TipoMedicacao");

                    b.Navigation("TipoMedicacao");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.Medicacoes.PrescricaoMedicacao", b =>
                {
                    b.HasOne("WEB_API_HealTime.Models.Medicacoes.Medicacao", "Medicacao")
                        .WithOne("PrescricaoMedicacao")
                        .HasForeignKey("WEB_API_HealTime.Models.Medicacoes.PrescricaoMedicacao", "MedicacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("PK_MedicacaoId_PrescricaoMedicao");

                    b.HasOne("WEB_API_HealTime.Models.Medicacoes.PrescricaoPaciente", "PrescricaoPaciente")
                        .WithMany("PrescricoesMedicacoes")
                        .HasForeignKey("PrescricaoPacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("PK_PrescricaoPacienteId_PrescricaoMedicao");

                    b.Navigation("Medicacao");

                    b.Navigation("PrescricaoPaciente");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.Medicacoes.PrescricaoPaciente", b =>
                {
                    b.HasOne("WEB_API_HealTime.Models.ConsultasMedicas.Medico", "Medico")
                        .WithMany("PrescricoesPacientes")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PrescricaoPaciente_Medico");

                    b.HasOne("WEB_API_HealTime.Models.Pessoas.Pessoa", "Pessoa")
                        .WithMany("PrescricaoPacientes")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PacienteId_PrescricoesPacientes");

                    b.Navigation("Medico");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.Pacientes.CuidadorPaciente", b =>
                {
                    b.HasOne("WEB_API_HealTime.Models.Pessoas.Pessoa", "PessoaCuidador")
                        .WithMany("CuidadorPaciente_Cuidador")
                        .HasForeignKey("CuidadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Pessoa_CuidadorPaciente_CuidadorId");

                    b.HasOne("WEB_API_HealTime.Models.Pessoas.Pessoa", "PessoaPaciente")
                        .WithMany("CuidadorPaciente_Pacientes")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Pessoa_CuidadorPaciente_PacienteId");

                    b.Navigation("PessoaCuidador");

                    b.Navigation("PessoaPaciente");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.Pacientes.ObservacaoPaciente", b =>
                {
                    b.HasOne("WEB_API_HealTime.Models.Pessoas.Pessoa", "Paciente")
                        .WithMany("ObservacoesPacientes")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_SqObservacao_Pessoas");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.Pacientes.ResponsavelPaciente", b =>
                {
                    b.HasOne("WEB_API_HealTime.Models.Pacientes.GrauParentesco", "GrauParentesco")
                        .WithMany("ResponsavelPacientes")
                        .HasForeignKey("GrauParentescoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_GrauParentescoId_GrauParentesco_ResponsavelPaciente");

                    b.HasOne("WEB_API_HealTime.Models.Pessoas.Pessoa", "Paciente")
                        .WithMany("ResponsavelPacientes_Pacientes")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_PacienteId_Pessoas_ResponsavelPaciente");

                    b.HasOne("WEB_API_HealTime.Models.Pessoas.Pessoa", "Responsavel")
                        .WithMany("ResponsavelPacientes_Responsavel")
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_ResponsavelId_Pessoas_ResponsavelPaciente");

                    b.Navigation("GrauParentesco");

                    b.Navigation("Paciente");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.Pessoas.ContatoPessoa", b =>
                {
                    b.HasOne("WEB_API_HealTime.Models.Pessoas.Pessoa", "Pessoa")
                        .WithOne("ContatoPessoa")
                        .HasForeignKey("WEB_API_HealTime.Models.Pessoas.ContatoPessoa", "PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Pessoa_ContatoPessoa_PessoaId");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.Pessoas.EnderecoPessoa", b =>
                {
                    b.HasOne("WEB_API_HealTime.Models.Pessoas.Pessoa", "Pessoa")
                        .WithOne("EnderecoPessoa")
                        .HasForeignKey("WEB_API_HealTime.Models.Pessoas.EnderecoPessoa", "PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_PK_EnderecoPessoa");

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.ConsultasMedicas.ConsultaAgendada", b =>
                {
                    b.Navigation("ConsultaCancelada");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.ConsultasMedicas.Especialidade", b =>
                {
                    b.Navigation("ConsultaAgendadas");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.ConsultasMedicas.Medico", b =>
                {
                    b.Navigation("ConsultaAgendadas");

                    b.Navigation("PrescricoesPacientes");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.ConsultasMedicas.StatusConsulta", b =>
                {
                    b.Navigation("ConsultasAgendadas");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.Medicacoes.Medicacao", b =>
                {
                    b.Navigation("PrescricaoMedicacao");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.Medicacoes.PrescricaoMedicacao", b =>
                {
                    b.Navigation("AndamentoMedicacoes");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.Medicacoes.PrescricaoPaciente", b =>
                {
                    b.Navigation("PrescricoesMedicacoes");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.Medicacoes.TipoMedicacao", b =>
                {
                    b.Navigation("Medicacoes");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.Pacientes.GrauParentesco", b =>
                {
                    b.Navigation("ResponsavelPacientes");
                });

            modelBuilder.Entity("WEB_API_HealTime.Models.Pessoas.Pessoa", b =>
                {
                    b.Navigation("ContatoPessoa");

                    b.Navigation("CuidadorPaciente_Cuidador");

                    b.Navigation("CuidadorPaciente_Pacientes");

                    b.Navigation("EnderecoPessoa");

                    b.Navigation("ObservacoesPacientes");

                    b.Navigation("PrescricaoPacientes");

                    b.Navigation("ResponsavelPacientes_Pacientes");

                    b.Navigation("ResponsavelPacientes_Responsavel");
                });
#pragma warning restore 612, 618
        }
    }
}
